apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-analyzer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: text-analyzer-app
  template:
    metadata:
      labels:
        app: text-analyzer-app
    spec:
      containers:
      - name: text-analyzer-app
        image: vvirta/text-analyzer-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: text-analyzer-service
spec:
  type: NodePort
  selector:
    app: text-analyzer-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
